slack:
  signingSecret: a-fake-secret
server:
  use-forward-headers: true
pubsub:
  consumerGroup: order-service
video-service:
  base-url:
  access-token-uri:
  client-id:
  client-secret:
spring:
  http:
    encoding:
      charset: UTF-8
      force: true
management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    export:
      prometheus:
        enabled: true
