apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  annotations:
    sidecar.jaegertracing.io/inject: jaeger
spec:
  template:
    metadata:
      name: order-service
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: order-service
        image: eu.gcr.io/boclips-prod/boclips/order-service:1
        env:
        - name: SENTRY_RELEASE
          value: order-service-$(VERSION)
        ports:
        - name: http
          containerPort: 8080
        envFrom:
        - secretRef:
            name: order-service
